services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # Any data to be shared between the container and the host
      - postgres_data:/var/lib/postgresql/data
      # Initialize database with correct schema
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - fitly_network

volumes:
  postgres_data:
    driver: local

networks:
  # Network already setup locally
  fitly_network:
    external: true
